name: Aviator Scraper Engine

on:
  schedule:
    - cron: '*/15 * * * *' # Se ejecuta cada 15 minutos automáticamente
  workflow_dispatch:      # Permite ejecutarlo manualmente desde el móvil

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install undetected-chromedriver selenium pandas

      - name: Run Scraper
        run: python main.py

      - name: Commit and Push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/historial.csv
          git commit -m "Update aviator data [skip ci]" || exit 0
          git push

